global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
  - job_name: 'my-application'
    honor_labels: true
    static_configs:
      - targets: ['flask-project:5000']
