global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
  - job_name: 'flask-project'
    honor_labels: true
    static_configs:
      - targets: ['flask-project:5000']
